{% set name = "tifffolder" %}
{% set version = "0.1.8" %}
{% set sha256 = "b7e82946c7ffe6d08d5b9d723a26deb942c040cec7977218079da4be59aac0bb" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - tifffile >=0.14.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - tifffolder

about:
  home: https://github.com/tlambert03/tifffolder
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Easily parse/access a subset of data from a folder of TIFFs
  description: |
    Parse filenames and lazily read subset of data from a folder 
    of images using numpy slicing syntax. Includes simplified file 
    pattern matching syntax and multithreaded file reading.
  dev_url: https://github.com/tlambert03/tifffolder

extra:
  recipe-maintainers:
    - tlambert03
