{% set name = "tifffolder" %}
{% set version = "0.1.7" %}
{% set sha256 = "b54c9e9c4db4eb49c3aa2768eb8f7add798f3983e29a09717d8a58951f0c4881" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy
    - tifffile >=0.14.0

test:
  imports:
    - tifffolder

about:
  home: https://github.com/tlambert03/tifffolder
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Easily parse/access a subset of data from a folder of TIFFs'
  description: |
    Parse filenames and lazily read subset of data from a folder 
    of images using numpy slicing syntax. Includes simplified file 
    pattern matching syntax and multithreaded file reading.
  dev_url: https://github.com/tlambert03/tifffolder

extra:
  recipe-maintainers:
    - tlambert03
