travis:
  secure:
    BINSTAR_TOKEN: aaMxn60CrV0aVDWtVCP8dlM44bQx5PxI5yK6RJRf1l1qxDiv7fa8PuJYpCIOQTS9ZfgI0se30ijFqT3KwPUgq0tVet1UrslqwiDEULHuMQEetcjr5w661cQbqrcEyzpNtQVosKgLa5bEkk6Pp7Of+YorPCr1+iJEnSlV8j63OHN89DlddzuZ+B+ZFzjBAnLoFx5wWiGEIJPIZC5C2hrQnexfXL8r0ve4HuPqKjYsbwacBJcmWQu1XcOl/14C9ML7abMcnnqY8IBM2PL+Aiz2ZHjm6MHOlyVAQrS1CYZ8yWnLCYLsKr0bWhaNpVjsNIT+aBiP4O4kDYRP4blOVIGpOYpCzSRrw+z6MW49SB23uo/xCx+SEOUXlDx73B3fqo8iO+ZqTgOpj/8+mUUcUMIl31WqjGY8qmRTBYuX5hy5PKvDjGN1wBMcj2tD4IEH/NeNL/Gcqzfdo44zYbL/XFWcef8tupPlROMhBTP9HOAXZbCHNU/R//lAz8fktjEoIQo5GUwphPqvdQ9dzcGD2kBLM+ozQMXuv2sdJCu4/HZmk1lWMlRTTA0eV8BF+SJVjizCaL35gwvbZ9P0h4LPntxkUgce6HDPn4tm40aY5fDCWeI8Vi29TWXbZBZq+lE6d+PjkUxIvKYsKO+x+DD0/u1TEuAXtHEN9IY7BdfAHzaNMdk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
