travis:
  secure:
    BINSTAR_TOKEN: Gue/UPCgPxODbYHl6QZ/NQenTfNFqLUg6j0KooeC35Cvhg2cgW14hFaMkONkQt0z05LO8hzksihzzxxnNuBmiXO/OK4Q0MuWzarf0s2IsmoyHUxkwh4pC6vDsYayBUfzWufKLVmmMUBFAADc2nxuEpkI7MKcxqIwYgioYccRXTMBjDs6DDzw/JWdPUc2O+VIcBbHRybOGi6bXpuqEgcp99b5+le7aRVlL6tHwifMAvn6yeWZ9jvN+z4vS65+8kldR5wNnPdbqqXbmq+eTLVKwGRw9KVxRcATfNiiJ5UBVRSzI7fjupFR8WoL5ghqI+f7OWp2FOCD+Tremu0Lc8K8wHrn9g+IdfRUgzV2vPfGVIRFRF0PXdCc+cjA1V+SvBnOj+Etp7kWuBI57MgDlqhuDRhMpq3hwJDvUyQES/MTrZcPQEi1fa75kuHui+qkuPhLkdiOOLrYXKxpyv6YHJQQUUNqyoDUJ2/Gwc5TKW0CcGr+dfUhaQ/RymJJYgM64wvA1Sl3n9Klj/KXO9BI0VefPvwmaUSpmJAGicEkvolGiUocB6gTjahHhl36YtzkHu4eMHXWV6sg4npenAJp3L7aPg4o38j6TuvZzfZZfU5eTcJ5/J1o5EgTeGm1bNuMWwjskmUWadyZwEvdXsYO26nClmZ1727DCr+IEcHr9XnOpx4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
